/**
 * Completed-crop PDF HTML builders (filesystem logo only; no DB / Puppeteer).
 */
const fs = require('fs');
const path = require('path');
const {
    formatPdfDate,
    formatPdfTimestamp,
    formatCurrency,
    formatQualityGrade,
    formatEnum,
    formatActivityLabel,
    formatActivityStatus,
    escapeHtml,
} = require('./completedCropExportPresentation');

let crmLogoBase64 = '';
try {
    const logoPath = path.join(__dirname, '../../src/assets/CRM-logo.png');
    if (fs.existsSync(logoPath)) {
        const logoData = fs.readFileSync(logoPath);
        crmLogoBase64 = `data:image/png;base64,${logoData.toString('base64')}`;
    }
} catch (err) {
    console.error('Failed to load CRM logo for PDF export:', err);
}

const buildActivityHistoryHtml = (activities) => {
    const rows = Array.isArray(activities) ? activities : [];
    if (rows.length === 0) {
        return `
            <div class="activity-section">
                <div class="activity-heading">
                    <div class="section-title activity-history-title">Activity History</div>
                </div>
                <div class="activity-empty">No activity records for this crop.</div>
            </div>
        `;
    }

    const includeNotes = rows.some((act) => String(act.notes || '').trim());
    const body = rows.map((act) => {
        const noteCell = includeNotes
            ? `<td class="notes-cell">${escapeHtml(String(act.notes || '').trim() || '—')}</td>`
            : '';
        return `
            <tr>
                <td>${escapeHtml(formatActivityLabel(act.activity_type))}</td>
                <td>${escapeHtml(formatPdfDate(act.planned_date))}</td>
                <td>${escapeHtml(formatPdfDate(act.actual_date))}</td>
                <td>${escapeHtml(formatActivityStatus(act.status))}</td>
                ${noteCell}
            </tr>
        `;
    }).join('');

    return `
        <div class="activity-section">
            <div class="activity-heading">
                <div class="section-title activity-history-title">Activity History</div>
            </div>
            <table class="activity-table">
                <thead>
                    <tr>
                        <th>Activity</th>
                        <th>Scheduled Date</th>
                        <th>Actual Date</th>
                        <th>Status</th>
                        ${includeNotes ? '<th>Notes</th>' : ''}
                    </tr>
                </thead>
                <tbody>
                    ${body}
                </tbody>
            </table>
        </div>
    `;
};

const buildCompletedCropsHtml = (rows, { generatedBy, generatedAt } = {}) => {
    const totalCount = rows.length;
    const totalYield = rows.reduce((sum, r) => sum + Number(r.yield_kg || 0), 0);
    const totalValue = rows.reduce((sum, r) => sum + Number(r.financial_value || 0), 0);
    const avgDuration = totalCount > 0
        ? rows.reduce((sum, r) => sum + Number(r.cycle_duration || 0), 0) / totalCount
        : 0;

    const exporterLine = generatedBy
        ? `Generated by: ${escapeHtml(generatedBy)} &bull; `
        : '';
    const generatedLabel = generatedAt || formatPdfTimestamp();

    const cardsHtml = rows.map((r) => `
        <div class="crop-card">
            <div class="crop-summary">
                <h2 class="crop-card-title">${escapeHtml(r.field_name || 'Unnamed Planting')}</h2>

                <div class="crop-grid">
                    <div class="crop-section">
                        <div class="section-title">Crop Information</div>

                        <div class="field-row">
                            <div class="field-label">Field Name</div>
                            <div class="field-value">${escapeHtml(r.field_name || '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Rice Variety</div>
                            <div class="field-value">${escapeHtml(r.crop_variety || '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Season</div>
                            <div class="field-value">${escapeHtml(formatEnum(r.cropping_season) || '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Establishment Method</div>
                            <div class="field-value">${escapeHtml(formatEnum(r.establishment_method) || '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Field Condition</div>
                            <div class="field-value">${escapeHtml(formatEnum(r.field_condition) || '—')}</div>
                        </div>
                    </div>

                    <div class="crop-section">
                        <div class="section-title">Crop Schedule</div>

                        <div class="field-row">
                            <div class="field-label">Planting Date</div>
                            <div class="field-value">${escapeHtml(r.planting_date ? formatPdfDate(r.planting_date) : '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Expected Harvest Date</div>
                            <div class="field-value">${escapeHtml(r.expected_harvest ? formatPdfDate(r.expected_harvest) : '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Actual Harvest Date</div>
                            <div class="field-value">${escapeHtml(r.harvest_date ? formatPdfDate(r.harvest_date) : '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Cycle Duration</div>
                            <div class="field-value">${r.cycle_duration !== null && r.cycle_duration !== undefined ? `${Number(r.cycle_duration)} Days` : '—'}</div>
                        </div>
                    </div>

                    <div class="crop-section">
                        <div class="section-title">Harvest Result</div>

                        <div class="field-row">
                            <div class="field-label">Yield</div>
                            <div class="field-value">${r.yield_kg !== null && r.yield_kg !== undefined ? `${Number(r.yield_kg).toLocaleString()} kg` : '—'}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Quality Grade</div>
                            <div class="field-value">${escapeHtml(formatQualityGrade(r.quality_grade) || '—')}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Financial Value</div>
                            <div class="field-value">${r.financial_value !== null && r.financial_value !== undefined ? formatCurrency(r.financial_value) : '—'}</div>
                        </div>
                        <div class="field-row">
                            <div class="field-label">Remarks</div>
                            <div class="field-value remarks-value">${escapeHtml(r.harvest_remarks || '—')}</div>
                        </div>
                    </div>
                </div>
            </div>

            ${buildActivityHistoryHtml(r.activities)}
        </div>
    `).join('');

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Completed Crop Records Report</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        body {
            font-family: 'Inter', sans-serif;
            color: #1e293b;
            margin: 0;
            padding: 0;
            font-size: 11px;
            line-height: 1.4;
            background-color: #ffffff;
        }
        .header {
            border-bottom: 2px solid #15803d;
            padding-bottom: 15px;
            margin-bottom: 25px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
        }
        .logo-container {
            display: flex;
            align-items: center;
            gap: 2px;
        }
        .logo-image {
            height: 48px;
            width: auto;
            display: block;
        }
        .logo-text {
            font-size: 22px;
            font-weight: 700;
            color: #0f172a;
            line-height: 1;
        }
        .logo-accent {
            color: #15803d;
        }
        .report-title-container {
            text-align: right;
        }
        .report-title {
            font-size: 15px;
            color: #0f172a;
            margin: 0 0 4px 0;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .report-meta {
            font-size: 10px;
            color: #64748b;
        }
        .kpi-container {
            display: flex;
            justify-content: space-between;
            gap: 12px;
            margin-bottom: 28px;
            page-break-inside: avoid;
            break-inside: avoid;
        }
        .kpi-card {
            flex: 1;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 14px 12px;
            text-align: center;
        }
        .kpi-value {
            font-size: 17px;
            font-weight: 700;
            color: #0f172a;
            margin-top: 6px;
        }
        .kpi-label {
            font-size: 9px;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 700;
        }
        .crop-card {
            /* 1pt + slightly stronger slate: print-stable on all cloned page-fragment edges */
            border: 1pt solid #cbd5e1;
            border-radius: 8px;
            margin-bottom: 24px;
            padding: 22px 24px;
            page-break-inside: auto;
            break-inside: auto;
            -webkit-box-decoration-break: clone;
            box-decoration-break: clone;
        }
        .crop-summary {
            page-break-inside: avoid;
            break-inside: avoid;
        }
        .crop-card-title {
            font-size: 17px;
            font-weight: 700;
            color: #15803d;
            margin: 0 0 18px 0;
            padding-bottom: 10px;
            border-bottom: 1px solid #e2e8f0;
            page-break-after: avoid;
            break-after: avoid;
        }
        .crop-grid {
            display: flex;
            align-items: stretch;
            gap: 0;
            page-break-inside: avoid;
            break-inside: avoid;
        }
        .crop-section {
            flex: 1;
            min-width: 0;
            padding: 4px 18px 6px;
        }
        .crop-section + .crop-section {
            border-left: 1px solid #e2e8f0;
        }
        .crop-section:first-child {
            padding-left: 0;
        }
        .crop-section:last-child {
            padding-right: 0;
        }
        .section-title {
            font-size: 11px;
            font-weight: 700;
            color: #475569;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 14px;
            page-break-after: avoid;
            break-after: avoid;
        }
        .field-row {
            margin-bottom: 13px;
        }
        .field-row:last-child {
            margin-bottom: 0;
        }
        .field-label {
            font-size: 10px;
            color: #64748b;
            margin-bottom: 4px;
        }
        .field-value {
            font-size: 12.5px;
            font-weight: 500;
            color: #0f172a;
            line-height: 1.5;
        }
        .remarks-value {
            white-space: pre-wrap;
            word-break: break-word;
        }
        /* Adaptive Activity History: fill remaining page space; split between rows only. */
        .activity-section {
            margin-top: 22px;
            page-break-inside: auto;
            break-inside: auto;
        }
        .activity-heading {
            page-break-after: avoid;
            break-after: avoid;
        }
        .activity-history-title {
            margin: 0 0 0 0;
            padding-bottom: 10px;
            border-bottom: 1px solid #e2e8f0;
            page-break-after: avoid;
            break-after: avoid;
        }
        .activity-table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            table-layout: fixed;
            margin-top: 12px;
            page-break-inside: auto;
            break-inside: auto;
            border: none;
            background-color: #ffffff;
        }
        .activity-table thead {
            display: table-header-group;
        }
        .activity-table tbody {
            display: table-row-group;
        }
        .activity-table th,
        .activity-table td {
            border: none;
            border-bottom: 1px solid #e2e8f0;
            padding: 9px 8px;
            vertical-align: top;
            word-break: break-word;
            background-color: #ffffff;
        }
        .activity-table th {
            text-align: left;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.4px;
            color: #475569;
            font-weight: 700;
            border-bottom: 1px solid #cbd5e1;
            page-break-after: avoid;
            break-after: avoid;
        }
        .activity-table td {
            font-size: 10px;
            color: #0f172a;
        }
        .activity-table tr {
            page-break-inside: avoid;
            break-inside: avoid;
        }
        .activity-table thead tr {
            page-break-inside: avoid;
            break-inside: avoid;
            page-break-after: avoid;
            break-after: avoid;
        }
        .notes-cell {
            white-space: pre-wrap;
            word-break: break-word;
        }
        .activity-empty {
            margin-top: 10px;
            font-size: 10px;
            color: #64748b;
            font-style: italic;
        }
        .no-records {
            text-align: center;
            padding: 40px;
            color: #64748b;
            font-style: italic;
            border: 1px dashed #cbd5e1;
            border-radius: 8px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo-container">
            ${crmLogoBase64 ? `<img src="${crmLogoBase64}" class="logo-image" alt="Logo" />` : ''}
            <div class="logo-text">Agri<span class="logo-accent">Track</span></div>
        </div>
        <div class="report-title-container">
            <h1 class="report-title">COMPLETED CROP RECORDS REPORT</h1>
            <div class="report-meta">${exporterLine}Generated: ${escapeHtml(generatedLabel)} &bull; Total Records: ${totalCount}</div>
        </div>
    </div>

    <div class="kpi-container">
        <div class="kpi-card">
            <div class="kpi-label">Completed Crops</div>
            <div class="kpi-value">${totalCount}</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-label">Total Yield</div>
            <div class="kpi-value">${totalYield.toLocaleString()} kg</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-label">Total Crop Value</div>
            <div class="kpi-value">${totalValue ? formatCurrency(totalValue) : '₱0.00'}</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-label">Average Crop Duration</div>
            <div class="kpi-value">${avgDuration.toFixed(1)} Days</div>
        </div>
    </div>

    <div class="records-container">
        ${totalCount > 0 ? cardsHtml : '<div class="no-records">No completed crop records found.</div>'}
    </div>
</body>
</html>
`;
};

module.exports = {
    buildCompletedCropsHtml,
    buildActivityHistoryHtml,
};
