process.env.NODE_ENV = 'test';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');

const {
    formatPdfDate,
    formatActivityLabel,
    formatRoleLabel,
} = require('../utils/completedCropExportPresentation');
const {
    buildCompletedCropsHtml,
    buildActivityHistoryHtml,
} = require('../utils/completedCropExportHtml');

describe('Completed crop PDF presentation helpers', () => {
    it('formats respondent-facing PDF dates as Month D, YYYY', () => {
        assert.equal(formatPdfDate('2026-01-20'), 'Jan 20, 2026');
        assert.equal(formatPdfDate('2026-05-18T00:00:00.000Z'), 'May 18, 2026');
        assert.equal(formatPdfDate(null), '—');
    });

    it('maps activity template keys to human-readable labels', () => {
        assert.equal(formatActivityLabel('transplanting'), 'Transplanting');
        assert.equal(formatActivityLabel('irrigation'), 'Irrigation Monitoring');
        assert.equal(formatActivityLabel('first_fertilizing'), 'Fertilizer #1');
        assert.equal(formatActivityLabel('pest_control'), 'Pest & Disease Monitoring');
        assert.equal(formatActivityLabel('second_fertilizing'), 'Fertilizer #2');
        assert.equal(formatActivityLabel('crop_monitoring'), 'Crop Monitoring');
        assert.equal(formatActivityLabel('final_pest_inspection'), 'Final Pest Inspection');
        assert.equal(formatActivityLabel('drain_irrigation'), 'Drain Irrigation');
        assert.equal(formatActivityLabel('harvesting'), 'Harvesting');
    });

    it('formats roles for Generated By display', () => {
        assert.equal(formatRoleLabel('admin'), 'Administrator');
        assert.equal(formatRoleLabel('ADMIN'), 'Administrator');
        assert.equal(formatRoleLabel('SECRETARY'), 'Secretary');
        assert.equal(formatRoleLabel('FARM_WORKER'), 'Farm Worker');
    });

    it('renders Field Name, Generated By, readable dates, and chronological Activity History', () => {
        const html = buildCompletedCropsHtml(
            [{
                planting_id: 92,
                field_name: 'Demo North Terrace',
                crop_variety: 'NSIC Rc110',
                cropping_season: 'DRY_SEASON',
                establishment_method: 'TRANSPLANTED',
                field_condition: 'IRRIGATED',
                planting_date: '2026-01-20',
                expected_harvest: '2026-05-20',
                harvest_date: '2026-05-18',
                cycle_duration: 118,
                yield_kg: 3450,
                quality_grade: 'A',
                financial_value: 103500,
                harvest_remarks: 'Dry-season irrigated transplanted NSIC Rc110.',
                activities: [
                    {
                        activity_type: 'transplanting',
                        planned_date: '2026-01-20',
                        actual_date: '2026-02-07',
                        status: 'COMPLETED',
                        notes: 'Seedlings transplanted.',
                    },
                    {
                        activity_type: 'harvesting',
                        planned_date: '2026-05-20',
                        actual_date: '2026-05-18',
                        status: 'COMPLETED',
                        notes: 'System: Record harvest date, yield quantity, and harvest completion.',
                    },
                ],
            }],
            {
                generatedBy: 'Development Admin (Administrator)',
                generatedAt: 'Sep 13, 2026, 12:07 PM',
            }
        );

        assert.match(html, /Field Name/);
        assert.equal(/Planting Name/.test(html), false);
        assert.match(html, /Generated by: Development Admin \(Administrator\)/);
        assert.match(html, /Generated: Sep 13, 2026, 12:07 PM/);
        assert.match(html, /Jan 20, 2026/);
        assert.match(html, /May 18, 2026/);
        assert.match(html, /Activity History/);
        assert.match(html, /Transplanting/);
        assert.match(html, /Harvesting/);
        assert.match(html, /Feb 7, 2026/);
        assert.match(html, /Completed Crops/);
        assert.match(html, /3,450 kg/);

        const transplantIdx = html.indexOf('>Transplanting<');
        const harvestIdx = html.indexOf('>Harvesting<');
        assert.ok(transplantIdx > -1 && harvestIdx > transplantIdx);
    });

    it('renders multi-record HTML without inventing activities and keeps crop sections separate', () => {
        const html = buildCompletedCropsHtml([
            {
                planting_id: 1,
                field_name: 'Field A',
                crop_variety: 'NSIC Rc110',
                cropping_season: 'DRY_SEASON',
                establishment_method: 'TRANSPLANTED',
                field_condition: 'IRRIGATED',
                planting_date: '2026-01-01',
                expected_harvest: '2026-05-01',
                harvest_date: '2026-04-30',
                cycle_duration: 119,
                yield_kg: 1000,
                quality_grade: 'A',
                financial_value: 1000,
                harvest_remarks: null,
                activities: [
                    {
                        activity_type: 'irrigation',
                        planned_date: '2026-01-10',
                        actual_date: '2026-01-11',
                        status: 'COMPLETED',
                        notes: '',
                    },
                ],
            },
            {
                planting_id: 2,
                field_name: 'Field B',
                crop_variety: 'NSIC Rc222',
                cropping_season: 'WET_SEASON',
                establishment_method: 'DIRECT_SEEDED',
                field_condition: 'RAINFED',
                planting_date: '2026-02-01',
                expected_harvest: '2026-06-01',
                harvest_date: '2026-05-28',
                cycle_duration: 116,
                yield_kg: 2000,
                quality_grade: 'B',
                financial_value: 2000,
                harvest_remarks: null,
                activities: [
                    {
                        activity_type: 'direct_seeding',
                        planned_date: '2026-02-01',
                        actual_date: '2026-02-01',
                        status: 'COMPLETED',
                        notes: '',
                    },
                ],
            },
        ], { generatedBy: 'Secretary User (Secretary)', generatedAt: 'Sep 13, 2026, 1:00 PM' });

        assert.match(html, /Total Records: 2/);
        assert.match(html, /Field A/);
        assert.match(html, /Field B/);
        assert.match(html, /Irrigation Monitoring/);
        assert.match(html, /Direct Seeding/);
        assert.equal(/Fake Harvesting/.test(html), false);
        assert.equal((html.match(/activity-history-title">Activity History</g) || []).length, 2);
        assert.equal((html.match(/class="crop-card"/g) || []).length, 2);
    });

    it('omits Notes column when no activity notes exist', () => {
        const withNotes = buildActivityHistoryHtml([
            {
                activity_type: 'irrigation',
                planned_date: '2026-01-10',
                actual_date: '2026-01-11',
                status: 'COMPLETED',
                notes: 'Flooded field.',
            },
        ]);
        assert.match(withNotes, /<th>Notes<\/th>/);

        const withoutNotes = buildActivityHistoryHtml([
            {
                activity_type: 'irrigation',
                planned_date: '2026-01-10',
                actual_date: '2026-01-11',
                status: 'COMPLETED',
                notes: '   ',
            },
        ]);
        assert.equal(/<th>Notes<\/th>/.test(withoutNotes), false);
    });

    it('uses adaptive Activity History pagination with clean horizontal separators', () => {
        const section = buildActivityHistoryHtml(
            Array.from({ length: 9 }, (_, i) => ({
                activity_type: i === 8 ? 'harvesting' : 'irrigation',
                planned_date: `2026-01-${String(i + 1).padStart(2, '0')}`,
                actual_date: `2026-01-${String(i + 1).padStart(2, '0')}`,
                status: 'COMPLETED',
                notes: `Row ${i + 1}`,
            }))
        );
        assert.match(section, /activity-section/);
        assert.equal(/activity-section--keep/.test(section), false);
        assert.equal(/activity-section--tall/.test(section), false);
        assert.match(section, /activity-history-title/);
        assert.match(section, /Harvesting/);

        const fullHtml = buildCompletedCropsHtml([{
            planting_id: 1,
            field_name: 'Demo',
            crop_variety: 'NSIC Rc110',
            cropping_season: 'DRY_SEASON',
            establishment_method: 'TRANSPLANTED',
            field_condition: 'IRRIGATED',
            planting_date: '2026-01-20',
            expected_harvest: '2026-05-20',
            harvest_date: '2026-05-18',
            cycle_duration: 118,
            yield_kg: 100,
            quality_grade: 'A',
            financial_value: 100,
            harvest_remarks: null,
            activities: Array.from({ length: 9 }, (_, i) => ({
                activity_type: 'irrigation',
                planned_date: '2026-02-01',
                actual_date: '2026-02-01',
                status: 'COMPLETED',
                notes: '',
            })),
        }]);

        // Adaptive pagination: section/table may break; rows and header must not.
        assert.match(fullHtml, /\.activity-section\s*\{[^}]*page-break-inside:\s*auto/s);
        assert.match(fullHtml, /\.activity-table\s*\{[^}]*page-break-inside:\s*auto/s);
        assert.match(fullHtml, /\.activity-table thead\s*\{[^}]*display:\s*table-header-group/s);
        assert.match(fullHtml, /\.activity-table tr\s*\{[^}]*page-break-inside:\s*avoid/s);
        assert.match(fullHtml, /\.activity-heading\s*\{[^}]*page-break-after:\s*avoid/s);
        assert.match(fullHtml, /\.activity-history-title\s*\{[^}]*border-bottom:\s*1px solid #e2e8f0/s);

        // Clean report table: no full-grid / vertical cell boxes.
        assert.match(fullHtml, /\.activity-table\s*\{[^}]*border:\s*none/s);
        assert.match(fullHtml, /\.activity-table th,\s*\.activity-table td\s*\{[^}]*border:\s*none/s);
        assert.match(fullHtml, /\.activity-table th,\s*\.activity-table td\s*\{[^}]*border-bottom:\s*1px solid #e2e8f0/s);
        assert.equal(/#94a3b8/.test(fullHtml), false);
        assert.equal(/border-right:\s*1px solid #94a3b8/.test(fullHtml), false);

        // Page-fragment rounded caps + branding polish.
        assert.match(fullHtml, /\.crop-card\s*\{[^}]*border:\s*1pt solid #cbd5e1/s);
        assert.match(fullHtml, /\.crop-card\s*\{[^}]*box-decoration-break:\s*clone/s);
        assert.match(fullHtml, /\.logo-image\s*\{[^}]*height:\s*48px/s);
        assert.match(fullHtml, /\.logo-container\s*\{[^}]*gap:\s*2px/s);
        assert.match(fullHtml, /crop-summary/);

        // Subtle three-column separators (not a boxed spreadsheet grid).
        assert.match(fullHtml, /\.crop-section \+ \.crop-section\s*\{[^}]*border-left:\s*1px solid #e2e8f0/s);
        assert.equal(/\.crop-grid\s*\{[^}]*border:\s*1px solid/s.test(fullHtml), false);
    });
});
